version: "3.9"

services:
    recipe-server:
        build: Dockerfile.localprod.server
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
    database-lprod:
        image: mongo:latest
        container_name: mongo
        ports:
            - "27017:27017"
        env_file:
            - .env.localprod
        restart: always
